"""Generates the Czech emoji name table from CLDR annotations.

Reads the CLDR ``common/annotations/cs.xml`` and
``common/annotationsDerived/cs.xml`` files (Unicode licence) and writes
``lib/features/chat/composer/emoji_czech_names.g.dart``. The ``tts`` annotation
becomes the display name, the keyword list becomes the search terms.

Usage: python tool/emoji/generate_czech_emoji_names.py <cs.xml> <derived.xml>
"""
from __future__ import annotations

import html
import re
import sys
from pathlib import Path

ANNOTATION = re.compile(r'<annotation cp="([^"]+)"( type="tts")?>([^<]*)</annotation>')

BACKSLASH = "\\"
QUOTE = "'"
DOLLAR = "$"


def parse(path: Path) -> tuple[dict[str, str], dict[str, list[str]]]:
    names: dict[str, str] = {}
    keywords: dict[str, list[str]] = {}
    for glyph, tts, text in ANNOTATION.findall(path.read_text(encoding="utf-8")):
        glyph = html.unescape(glyph)
        text = html.unescape(text).strip()
        if not text:
            continue
        if tts:
            names[glyph] = text
        else:
            keywords[glyph] = [part.strip() for part in text.split("|") if part.strip()]
    return names, keywords


def dart_string(value: str) -> str:
    escaped = (
        value.replace(BACKSLASH, BACKSLASH + BACKSLASH)
        .replace(QUOTE, BACKSLASH + QUOTE)
        .replace(DOLLAR, BACKSLASH + DOLLAR)
    )
    return QUOTE + escaped + QUOTE


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        print(__doc__, file=sys.stderr)
        return 2
    names: dict[str, str] = {}
    keywords: dict[str, list[str]] = {}
    for source in argv[1:]:
        found_names, found_keywords = parse(Path(source))
        names.update(found_names)
        keywords.update(found_keywords)
    output = (
        Path(__file__).resolve().parents[2]
        / "lib/features/chat/composer/emoji_czech_names.g.dart"
    )
    lines = [
        "// GENERATED by tool/emoji/generate_czech_emoji_names.py from CLDR",
        "// common/annotations/cs.xml and common/annotationsDerived/cs.xml.",
        "// Unicode CLDR data, see https://www.unicode.org/license.txt.",
        "// Do not edit by hand.",
        "",
        "part of 'emoji_picker.dart';",
        "",
        "const Map<String, EmojiTranslation> _cldrCzechEmoji =",
        "    <String, EmojiTranslation>{",
    ]
    for glyph in sorted(names):
        terms = [term for term in keywords.get(glyph, []) if term != names[glyph]]
        joined = ", ".join(dart_string(term) for term in terms)
        lines.append(
            f"  {dart_string(glyph)}: EmojiTranslation("
            f"name: {dart_string(names[glyph])}, keywords: <String>[{joined}]),"
        )
    lines.append("};")
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"{len(names)} glyphs -> {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
