from __future__ import annotations

# ruff: noqa: E402, F401

import json
import sys
from pathlib import Path
from typing import Any

from openapi_spec_validator import validate


MODULE_ROOT = Path(__file__).resolve().parent
if str(MODULE_ROOT) not in sys.path:
    sys.path.insert(0, str(MODULE_ROOT))

from validator_signaling_common import (
    CONTRACT_ROOT,
    EXPECTED_HPB_SHA,
    EXPECTED_OPERATIONS,
    EXPECTED_TALK_SHA,
    FIXTURE_ROOT,
    MANIFEST_PATH,
    SHA,
    ContractValidationError,
    decode_json_bytes,
    find_operation,
    load_json,
    normalize_hpb_endpoint,
    normalize_nextcloud_server,
    require_integer,
    require_object,
    require_string,
    require_unique_cases,
)
from validator_signaling_hpb import validate_hpb_case
from validator_signaling_http import validate_http_case
from validator_signaling_runtime import simulate_runtime, validate_runtime_case
from validator_signaling_settings import validate_settings_case


SECRET_FIELDS = {"ticket", "credential"}


def scan_fixture_secrets(value: Any, path: str = "$") -> None:
    if isinstance(value, dict):
        for key, child in value.items():
            child_path = f"{path}.{key}"
            secret_token = key == "token" and any(
                marker in path
                for marker in ("helloAuthParams", ".auth.params", ".federation")
            )
            if (key in SECRET_FIELDS or secret_token) and isinstance(child, str):
                if not child.startswith("synthetic-"):
                    raise ContractValidationError(
                        f"Non-synthetic secret-shaped fixture at {child_path}"
                    )
            scan_fixture_secrets(child, child_path)
    elif isinstance(value, list):
        for index, child in enumerate(value):
            scan_fixture_secrets(child, f"{path}[{index}]")


def scan_repository_text(paths: set[Path]) -> None:
    forbidden = (
        "BEGIN " + "PRIVATE KEY",
        "Authorization" + ": Basic",
        "Co-Authored" + "-By:",
        "Generated " + "with " + "Clau" + "de",
        "Generated by " + "Chat" + "GPT",
    )
    for path in paths:
        text = path.read_text(encoding="utf-8")
        for marker in forbidden:
            if marker in text:
                raise ContractValidationError(
                    f"Forbidden repository marker in {path.name}"
                )


def validate_operations(document: dict[str, Any]) -> int:
    operations = {
        operation_id: find_operation(document, operation_id)
        for operation_id in EXPECTED_OPERATIONS
    }
    for operation_id, (method, suffix) in EXPECTED_OPERATIONS.items():
        path, actual_method, _ = operations[operation_id]
        if actual_method != method or not path.endswith(suffix):
            raise ContractValidationError(f"OpenAPI operation {operation_id} drifted")
    return len(operations)


def validate_fixture_cases(
    manifest: dict[str, Any],
    expected_counts: dict[str, Any],
    document: dict[str, Any],
) -> tuple[dict[str, int], set[Path]]:
    fixture_specs = (
        ("httpFile", "http"),
        ("settingsFile", "settings"),
        ("hpbFile", "hpb"),
        ("runtimeFile", "runtime"),
    )
    listed_paths: set[Path] = set()
    counts: dict[str, int] = {"operations": len(EXPECTED_OPERATIONS), "runtimeSteps": 0}
    for manifest_key, label in fixture_specs:
        path = (
            FIXTURE_ROOT / require_string(manifest.get(manifest_key), manifest_key)
        ).resolve()
        listed_paths.add(path)
        expected_count = require_integer(expected_counts.get(label), f"{label} count")
        cases = require_unique_cases(load_json(path), expected_count, label)
        for case in cases:
            scan_fixture_secrets(case)
            if label == "http":
                validate_http_case(document, case)
            elif label == "settings":
                validate_settings_case(case)
            elif label == "hpb":
                validate_hpb_case(case)
            else:
                counts["runtimeSteps"] += validate_runtime_case(case)
        counts[label] = len(cases)
    return counts, listed_paths


def validate_contract() -> dict[str, int]:
    manifest = require_object(load_json(MANIFEST_PATH), "manifest")
    if manifest.get("talkSha") != EXPECTED_TALK_SHA or not SHA.fullmatch(
        str(manifest.get("talkSha", ""))
    ):
        raise ContractValidationError("Talk SHA is not pinned to the accepted revision")
    if manifest.get("hpbSha") != EXPECTED_HPB_SHA or not SHA.fullmatch(
        str(manifest.get("hpbSha", ""))
    ):
        raise ContractValidationError("HPB SHA is not pinned to the accepted revision")
    expected_counts = require_object(manifest.get("expectedCounts"), "expectedCounts")

    contract_path = (
        FIXTURE_ROOT / require_string(manifest.get("contract"), "contract")
    ).resolve()
    document = require_object(load_json(contract_path), "OpenAPI document")
    validate(document)
    operation_count = validate_operations(document)
    counts, listed_paths = validate_fixture_cases(
        manifest,
        expected_counts,
        document,
    )
    counts["operations"] = operation_count

    actual_paths = {
        path.resolve()
        for path in FIXTURE_ROOT.glob("*.json")
        if path.name != MANIFEST_PATH.name
    }
    if listed_paths != actual_paths:
        raise ContractValidationError("Signaling manifest does not cover every fixture")
    module_paths = {
        path.resolve() for path in CONTRACT_ROOT.glob("validator_signaling_*.py")
    }
    scan_repository_text(
        listed_paths
        | module_paths
        | {
            MANIFEST_PATH.resolve(),
            contract_path,
            Path(__file__).resolve(),
            (CONTRACT_ROOT / "test_validate_contract.py").resolve(),
            (CONTRACT_ROOT / "requirements.txt").resolve(),
        }
    )
    return counts


def main() -> int:
    try:
        counts = validate_contract()
        print(
            "Validated 1 OpenAPI document, "
            f"{counts['operations']} HTTP operations, "
            f"{counts['http']} HTTP cases, "
            f"{counts['settings']} settings cases, "
            f"{counts['hpb']} HPB frames and "
            f"{counts['runtime']} runtime cases with "
            f"{counts['runtimeSteps']} state transitions."
        )
        return 0
    except (
        ContractValidationError,
        KeyError,
        OSError,
        TypeError,
        ValueError,
        json.JSONDecodeError,
    ) as error:
        print(f"Contract validation failed: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
