/// Stable error categories emitted while validating untrusted wire data.
enum TalkProtocolErrorCode {
  invalidServerAddress,
  insecureServerAddress,
  invalidServerHost,
  invalidServerPath,
  invalidServerStatus,
  invalidLoginInitialization,
  untrustedLoginEndpoint,
  invalidLoginCredentials,
  untrustedCredentialServer,
  invalidCapabilities,
  ocsFailure,
  invalidConversationIdentifier,
  invalidConversationRequest,
  invalidConversationResponse,
  invalidConversationHeaders,
  duplicateConversationToken,
  previewConversationMismatch,
  invalidConversationMerge,
  invalidRecipientSearchRequest,
  invalidRecipientSearchResponse,
  invalidCreateConversationRequest,
  invalidCreateConversationResponse,
  invalidParticipantsRequest,
  invalidParticipantsResponse,
  invalidRoomSettingsRequest,
  invalidRoomSettingsResponse,
  invalidBansRequest,
  invalidBansResponse,
  invalidBotsRequest,
  invalidBotsResponse,
  invalidChatIdentifier,
  invalidChatProfile,
  invalidChatRequest,
  invalidChatResponse,
  invalidChatHeaders,
  invalidChatState,
  invalidChatMerge,
  invalidChatOutbox,
  invalidSharedItemsRequest,
  invalidSharedItemsResponse,
  invalidTranslationRequest,
  invalidTranslationResponse,
  invalidLocationShareRequest,
  invalidLocationShareResponse,
  invalidPollRequest,
  invalidPollResponse,
  invalidRichChatProfile,
  invalidRichChatRequest,
  invalidRichChatResponse,
  invalidRichChatRender,
  invalidRichChatState,
  invalidRichChatMerge,
  invalidAttachmentIdentifier,
  invalidAttachmentProfile,
  invalidAttachmentModel,
  invalidAttachmentRequest,
  invalidAttachmentResponse,
  invalidAttachmentDavPath,
  invalidAttachmentDavXml,
  invalidAttachmentState,
  invalidAttachmentRuntime,
  invalidSignalingIdentifier,
  invalidSignalingProfile,
  invalidSignalingSettings,
  invalidSignalingRequest,
  invalidSignalingResponse,
  invalidSignalingFrame,
  invalidSignalingState,
  invalidSignalingRuntime,
  invalidCallProfile,
  invalidCallRequest,
  invalidCallResponse,
  invalidCallState,
  invalidPushIdentifier,
  invalidPushOrigin,
  invalidPushCryptoMaterial,
  invalidPushEnvelope,
  invalidPushPayload,
  invalidPushRegistration,
  invalidPushState,
  invalidPushCryptoResult,
  invalidListedRoomsRequest,
  invalidListedRoomsResponse,
  invalidFederationInvitationRequest,
  invalidFederationInvitationResponse,
  invalidRemoteFilesRequest,
  invalidRemoteWipeRequest,
  invalidRemoteWipeResponse,
  invalidRemoteFilesResponse,
  invalidSearchIdentifier,
  invalidSearchRequest,
  invalidSearchResponse,
  unsupportedChatOperation,
  unsupportedAttachmentOperation,
  unsupportedSignalingOperation,
  unsupportedCallOperation,
  unsupportedPushOperation,
  unsupportedHttpStatus,
}

/// A redacted protocol error that never includes an untrusted field value.
final class TalkProtocolException implements Exception {
  const TalkProtocolException(this.code, {required this.path});

  final TalkProtocolErrorCode code;
  final String path;

  @override
  String toString() => 'TalkProtocolException(code: ${code.name}, path: $path)';
}

Never protocolFailure(TalkProtocolErrorCode code, String path) =>
    throw TalkProtocolException(code, path: path);
