import 'package:nextcloudtalk/data/app_database.dart';
import 'package:talk_protocol/talk_protocol.dart';

StoredAttachmentJob pendingAttachmentFixture(
  int index, {
  String phase = 'uploading',
  int count = 4,
  String accountId = 'account-a',
  String roomToken = 'rooma123',
  String albumId = 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
}) => StoredAttachmentJob(
  accountId: accountId,
  jobId: 'aaaaaaaa-aaaa-4aaa-8aaa-${index.toRadixString(16).padLeft(12, '0')}',
  serverUrl: 'https://cloud.example.invalid',
  capabilityGeneration: 1,
  replayContractRevision: attachmentReplayContractRevision,
  davUserId: 'fixture-user',
  roomToken: roomToken,
  referenceId: ChatPhotoAlbumReference(
    albumId: albumId,
    index: index,
    count: count,
  ).referenceId,
  sourceHandle: 'nctalk-media-v1:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
  sourceOwnership: 'appOwnedCopy',
  sourceByteLength: 1024,
  sourceSha256: 'a' * 64,
  sourceMimeType: 'image/png',
  sourceDisplayName: 'photo-$index.png',
  messageKind: 'file',
  silent: index > 0,
  enqueueSequence: index + 1,
  normalUploadMaximumBytes: 2048,
  chunkSizeBytes: 1024000,
  phase: phase,
  chunkCollectionReady: false,
  chunkManifestLoaded: false,
  verifiedChunksJson: '[]',
  attemptCount: 1,
  finalizationDispatched:
      phase == 'completed' || phase == 'awaitingConfirmation',
  cleanupChunkSession: false,
  cleanupDraftFile: false,
  messageIdsJson: phase == 'completed' ? '[${100 + index}]' : '[]',
  profileFederated: false,
  profileEnabled: true,
  profileCaption: true,
  profileVoice: true,
  profileReply: true,
  profileThreads: true,
  profileSilent: true,
  roomCanWrite: true,
  automaticRetryCount: 0,
  sourceReleased: true,
  createdAtMillis: 1000 + index,
  updatedAtMillis: 1000 + index,
);
